
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5751d45fbde18849c539418a29a4404f54cebe8baeeec208409674edcbbbc63b4df19f08cf9539e9533f71eefce336e3a97b1ddec581b4cf0de2ff089763e2c6
  s3_secret: BTl/CZ5ebgX3qbHPeYpXw6LThVNLq9pH8TmETuGX
  sendgrid_user: app21414705@heroku.com
  sendgrid_pwd: j1tzfb59
  stripe_secret: sk_test_N7UZshZYAONoRj5eyV0WtH8f
  stripe_pk: pk_test_IVRbMpgxt78N8kheMNLN55Og
  facebook_app_id: 255319931309644
  facebook_app_secret: e3425af478b555c09bffbbfb834d1e22

test:
  secret_key_base: 9064b478827feee0791470ee00a36de59c4f38c0eee47c58252acf1cf2359641d9102bb48bb61a86405e4b36e80fe73d1162903cc3d70089cbae6cc4d782bbce
  s3_secret: BTl/CZ5ebgX3qbHPeYpXw6LThVNLq9pH8TmETuGX

production:
  secret_key_base: a9c6f2325ccf3d8fefb7765f7f86804d78d3b95a29fc2c81c572302456c3963735fea1007c9bf04075708e3509d8d880ad12b180674b7be9141d12281330b32a
  s3_secret: BTl/CZ5ebgX3qbHPeYpXw6LThVNLq9pH8TmETuGX
  facebook_app_id: 243658872479364
  facebook_app_secret: 03ad5cc9fdd3066ac43a6ef14eae97d7